my:
  datasource:
    mysql:
      jdbcUrl: jdbc:mysql://localhost:3306/springbatch?userSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 19980928
      driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    username: root
    password: 19980928
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbatch?userSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  #    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
  #    type: com.alibaba.druid.pool.DruidDataSource
  batch:
    initialize-schema: always
    name1: 1231
    job:
      names: listenerJob,parameterJob,deciderDemoJob
      # parentJob,flowDemoJob,listenerJob #配置要启动的job名称，   逗号分隔
  profiles:
    include: com.hewen
logging:
#  level: info
  file:
    name: ./logs/application.log
