server:
  port: 80
#Eureka配置
#服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false #不向eureka中注册自己
  instance:
    instance-id: 何文消费端 #${spring.application.name} #修改默认的描述，改别的配置文件看起来拿不到，但是其实拿得到
    prefer-ip-address: true #是否将ip也注册到eurekaServer上
    lease-renewal-interval-in-seconds: 10 #客户端发送心跳的频率
    lease-expiration-duration-in-seconds: 15 #告诉服务端我多少秒之内没发心跳就移除我的服务
spring:
  application:
    name: 何文大沙雕啊
# 开启hystrix
feign:
#  hystrix:
#    enabled: true # 启动hystrix熔断机制
  circuitbreaker:
    enabled: true
info:
  app.name: 何文大沙雕啊22
