server:
  port: 3060
spring:
  application:
    name: Hewen's SpringCloud-GateWay-Zuul-3060
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
  instance:
    instance-id: 何文菜鸡网关
    prefer-ip-address: true # 隐藏ip
info:
  app.name: HewenLsy
  company.name: CIB
  version: 1.0.0
# 用了网关，不
zuul:
  routes:
    mytee:
      serviceId: springcloud-provider-dept
      path: /mydept/**
      # 如果只这么设置，其实不会影响原有的路由映射，但是如果加了下面的ignored-services，就会变成只路由开放的服务
      # 可以伪装域名和服务名，是很好的
  ignored-services: '*' #不路由的服务路径
  prefix: /hewen
  #公共的访问前缀
#  host:
#    connect-timeout-millis: 3000
#    socket-timeout-millis: 3000
#ribbon:
#  ReadTimeout: 3000
#  ConnectTimeout: 3000