server:
  port: 8001

#Mybatis配置
mybatis:
  type-aliases-package: com.hewen.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?userSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19980928
  profiles:
    include: eureka

##Eureka配置
##服务注册到哪里
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#  instance:
#    instance-id: 何文大沙雕 #修改默认的描述
#    prefer-ip-address: false #是否将ip也注册到eurekaServer上
#    lease-renewal-interval-in-seconds: 10 #客户端发送心跳的频率
#    lease-expiration-duration-in-seconds: 30 #告诉服务端我多少秒之内没发心跳就移除我的服务
# info信息
info:
  app.name: ${spring.application.name}
  company.name: hewencpy
# 健康检查
management:
  server:
    port: 12138
  endpoints:
    web:
      exposure:
        include: "*"
