server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: eureka7003.com #服务器实例名
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #如果是false，则表示自己为注册中心，表示自己就是一个注册中心，不需要去检索什么服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
    #就是监控页面
    #public EurekaClientConfigBean() {
    #        this.serviceUrl.put("defaultZone", "http://localhost:8761/eureka/");
    #默认就把上面的替换掉了，约定大于配置
  server:
    enable-self-preservation: true
spring:
  profiles:
    include: log4j
#logging:
#  level: info